services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vimgenius_production
      POSTGRES_USER: vimgenius
      POSTGRES_PASSWORD: vimgenius_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "
        bundle exec rails db:create &&
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails server -b 0.0.0.0 -p 3000 -e production
      "
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://vimgenius:vimgenius_password@db:5432/vimgenius_production
      RAILS_ENV: production
      SECRET_KEY_BASE: 830ff5a9c3a0231fe69b5c552750edace0f4676676641243d8b7caa1a581bfd0b18ed55ba6fee0073de73c954a4a98edd56f313eab1b8ff589011b76be20baf9
    volumes:
      - .:/app

volumes:
  postgres_data: