global: &global
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: 5
  host: localhost

development:
  database: vim_genius_development
  <<: *global

test: &test
  database: vim_genius_test
  <<: *global

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: vimgenius_production
  username: vimgenius
  password: vimgenius_password
  host: db
  port: 5432
  <<: *global

cucumber:
  <<: *test
